ourhockey/manage_ourhockey_site/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

ourhockey/ourhockey_playermanager/urls.py
from django.conf.urls import patterns, url
from ourhockey_playermanager import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.PlayerModelView.as_view(), name='index'),
    url(r'^player_insert/$', views.insert_player, name='player_insert'),
   # url(r'^player_update/$', views.PlayerUpdateView.as_view(), name='player_update'),
    url(r'^player_list/$', views.PlayerListView.as_view(), name='player_list'),
    url(r'^player_detail/(?P<pk>\d+)/$', views.PlayerDetailView.as_view(), name='player_detail'),
    url(r'^player_attend_list/$', views.update_attend, name='player_attend_list'),
]

ourhockey/ourhockey_sitemanager/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from ourhockey_common import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^playermanager/', include('ourhockey_playermanager.urls', namespace="playermanager")),
]

ourhockey/ourhockey_common/models.py
from __future__ import unicode_literals

from django.db import models

class Person(models.Model):
    name = models.CharField(max_length=200)  # Name
    birthday = models.DateField()  # Birthday 
    gender = models.CharField(max_length=10)  # Gender: male or female
    adult = models.BooleanField(default=True)  # Adult: True - Adult, False - Junior

    def __unicode__(self):  # __str__ on Python3
        return self.name

ourhockey/ourhockey_playermanager/models.py
from __future__ import unicode_literals

import os.path

from unidecode import unidecode
from django.conf import settings
from django.db import models
from ourhockey_common.models import Person


def get_upload_to(instance, filename):
    # Dumb proxy to instance method.
    return instance.get_upload_to(filename)


class Player(Person):
    back_number = models.IntegerField(default=0)  # Player Back Number
    duty = models.CharField(max_length=255)  # Player Duty
    position = models.CharField(max_length=2)  # Player Position
    member_level = models.CharField(max_length=2, default="03")  # Player Member Level
                                                                        # 00: Member / 01: Pre Member / 02: Guest / 
                                                                        # 03: None Level(default) / 04: Officer
    state = models.CharField(max_length=2, default="00")  # 00: alive / 01: Pause / 02: Not attend
    profile_image = models.ImageField(upload_to=get_upload_to)
    attend = models.BooleanField(default=False)   
                
    def __unicode__(self):  # __str__ on Python3
        return self.name
    
    def get_upload_to(self, filename):
        folder_name = 'static/photo/ourhockey_player/profiles'
        filename = self.profile_image.field.storage.get_valid_name(filename)

        # do a unidecode in the filename and then
        # replace non-ascii characters in filename with _ , to sidestep issues with filesystem encoding
        filename = "".join((i if ord(i) < 128 else '_') for i in unidecode(filename))

        # Truncate filename so it fits in the 100 character limit
        # https://code.djangoproject.com/ticket/9893
        while len(os.path.join(folder_name, filename)) >= 95:
            prefix, dot, extension = filename.rpartition('.')
            filename = prefix[:-1] + dot + extension
        # return filename
        return os.path.join(folder_name, filename)

ourhockey/ourhockey_playermanager/forms.py
from django import forms

class AttendCheckForm(forms.Form):
    attend = forms.BooleanField(required=True)
    
    
class InsertPlayerForm(forms.Form):
    name = forms.CharField(max_length=200)
    birthday = forms.DateField()
    gender_choices = (('1', 'Male'), ('2', 'Female'))
    gender = forms.ChoiceField(widget=forms.RadioSelect, choices=gender_choices)
    
    """
    if birthday is over 19 years
        adult_checked == true
    is it possible to automatically checked block after input the birthday value? 
    """
    adult = forms.CheckboxInput()
    back_number = forms.IntegerField()
    duty = forms.RadioSelect()
    position = forms.RadioSelect()
    profile_image = forms.ImageField()

ourhockey/ourhockey_common/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    
    template_name = 'home.html'
    
    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['object_list'] = ['playermanager']
        return context

ourhockey/ourhockey_playermanager/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView

from ourhockey_playermanager.models import Player
from ourhockey_playermanager.forms import AttendCheckForm, InsertPlayerForm

# Add logging
import logging
from rest_framework.urls import template_name
from __builtin__ import False
from Carbon.Aliases import false
logger = logging.getLogger(__name__)


class PlayerModelView(TemplateView):
    template_name = 'ourhockey_playermanager/index.html'
    
    def get_context_data(self, **kwargs):
        context = super(PlayerModelView, self).get_context_data(**kwargs)
        context['object_list'] = ['player_insert', 'player_list']
        return context


class PlayerListView(ListView):
    template_name = 'ourhockey_playermanager/player_list.html'
    context_object_name = 'player_list'
    
    def get_queryset(self):
        return Player.objects.order_by('-birthday')[:5]
    
class PlayerDetailView(DetailView):
    model = Player
    
    
# -- Function-based View
def update_attend(request):
    
    origin_player_list = Player.objects.filter(attend=True)
    
    for player in origin_player_list:
        player.attend = False
        player.save()
    
    if request.POST:
        form = AttendCheckForm(request.POST)

        if form.is_valid():
            for player_id in request.POST.getlist('attend'):
                attend_player = get_object_or_404(Player, pk=int(player_id))
                attend_player.attend = True
                attend_player.save()           
        else:
            logger.debug("update_attend() not form.is_valid()")
            return render(request, 'ourhockey_playermanager/player_list.html', {
                            'error_message': "What's wrong with you!!!!",
                    })
        
    else:
        return HttpResponseRedirect('')

    player_attend_list = Player.objects.filter(attend=True)
      
    return render(request, 'ourhockey_playermanager/player_attend_list.html', {
        'player_attend_list': player_attend_list,
    })


def insert_player(request):
    
    if request.POST:
        insert_player_form = InsertPlayerForm(request.POST)
        
        if insert_player_form.is_valid():
            
            return HttpResponseRedirect('ourhockey_playermanager/player_list.html')
        
    else:
        insert_player_form = InsertPlayerForm()
    
    return render(request, 'ourhockey_playermanager/player_insert.html', 
                  {'form': insert_player_form})

ourhockey/ourhockey_common/templates/ourhockey_common/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}My Hockey Management Site{% endblock %}</title>
</head>

<body>
	<div id="sidebar">
		{% block sidebar %}
		<ul>
			<li><a href="/">Project_Home</a></li>
			<li><a href="/admin">Admin</a></li>
		</ul>
		{% endblock %}
		<br>
	</div>
	
	<div id="content">
		{% block content %}{% endblock %}
	</div>
</body>
</html>

ourhockey/ourhockey_common/templates/ourhockey_common/base_player.html
{% extends "base.html" %}

<title>{% block title %}Players Application Site{% endblock %}</title>

{% block sidebar %}
{{ block.super }}
<ul>
	<li><a href="/playermanager/">Players_Home</a></li>
</ul>
{% endblock %}

ourhockey/ourhockey_common/templates/ourhockey_common/base_players.html
{% extends "base.html" %}

<title>{% block title %}Players Application Site{% endblock %}</title>

{% block sidebar %}
{{ block.super }}
<ul>
	<li><a href="/players/">Players_Home</a></li>
</ul>
{% endblock %}

ourhockey/ourhockey_common/templates/ourhockey_common/home.html
{% extends "base.html" %}

{% block content %}
	<h2>My Application</h2>
	<ul>
		{% for app_name in object_list %}
			{% with app_name|add:":"|add:"index" as url_var %}
			<li><a href="{% url url_var %}">{{ app_name }}</a></li>
			{% endwith %}
		{% endfor %}
	</ul>

{% endblock content %}

ourhockey/ourhockey_playermanager/templates/ourhockey_playermanager/index.html
{% extends "base_player.html" %}

{% block content %}
	<h2>Player Management System</h2>
	<ul>
		{% for model_name in object_list %}
			{% with "PlayerManager:"|add:model_name|lower as urlvar %}
			<li><a href="{% url urlvar %}">{{ model_name }}</a></li>
			{% endwith %}
		{% endfor %}
	</ul>
{% endblock content %}

ourhockey/ourhockey_playermanager/templates/ourhockey_playermanager/player_attend_list.html
{% extends "base_player.html" %}

{% block content %}

<h1>Player Attend List</h1>

{% if player_attend_list %}
	{% for player in player_attend_list %}
		{% if player.attend == True %}
			<input type="checkbox" name="attend" value="{{ player.id }}" checked="checked"/>
		{% else %}
			<input type="checkbox" name="attend" value="{{ player.id }}"/>
		{% endif %}
		<a href="{% url 'playermanager:player_detail' player.id %}">
		{% if player.profile_image %}
			{% load staticfiles %}
			<img src="{% static player.profile_image %}" alt="" width="150" height="150"/>
		{% endif %}
   		{{ player.name }}</br>
   		</a>
	{% empty %}
		<li>Sorry, no Player in this list.</li></br>
	{% endfor %}
	</ul>
{% else %}
	<p>No players are available.</p>
{% endif %}

{% endblock content %}

ourhockey/ourhockey_playermanager/templates/ourhockey_playermanager/player_detail.html
{% extends "base_player.html" %}

{% block content %}

<h1>{{ player.name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<li>
{% if player.profile_image %}
{% load staticfiles %}
	<img src="{% static player.profile_image %}" alt=""/>
{% endif %}
</li>
<li><label>{{ player.name }}</label></br></li>
<li><label>{{ player.back_number }}</label></br></li>
<li><label>{{ player.duty }}</label></br></li>
<li><label>{{ player.position }}</label></br></li>
<li><label>{{ player.memeber_level }}</label></br></li>
<li><label>{{ player.state }}</label></br></li>


{% endblock content %}

ourhockey/ourhockey_playermanager/templates/ourhockey_playermanager/player_insert.html
{% extends "base_player.html" %}

<form action="" method=POST>
	{% csrf_token %}
	{{ form.as_p }}
	<p><input type="submit" value="Insert Player" /></p>
</form>

ourhockey/ourhockey_playermanager/templates/ourhockey_playermanager/player_list.html
{% extends "base_player.html" %}

{% block content %}

<h1>Player Attend List</h1>

{% if player_list %}
	<form action="{% url 'playermanager:player_attend_list' %}" method="post">
	{% csrf_token %}
	{% for player in player_list %}
		{% if player.attend %}
			<input type="checkbox" name="attend" value="{{ player.id }}" checked="checked"/>
		{% else %}
			<input type="checkbox" name="attend" value="{{ player.id }}"/>
		{% endif %}
		<a href="{% url 'playermanager:player_detail' player.id %}">
		{% if player.profile_image %}
			{% load staticfiles %}
			<img src="{% static player.profile_image %}" alt="" width="150" height="150"/>
		{% endif %}
   		{{ player.name }}</br>
   		</a>
	{% empty %}
		<li>Sorry, no Player in this list.</li></br>
	{% endfor %}
	<input type="submit" value="Attend"/>
	</form>
	</ul>
{% else %}
	<p>No players are available.</p>
{% endif %}

{% endblock content %}

ourhockey/ourhockey_playermanager/templates/ourhockey_playermanager/player_update.html
{% extends "base_player.html" %}